language: ruby

services:
  - docker

before_install:
  - docker build -t xiaodi93/rpi-php:latest --build-arg PHP_VERSION=7.3 ./php
  - docker build -t xiaodi93/rpi-php:7.2 --build-arg PHP_VERSION=7.2 ./php
  - docker build -t xiaodi93/rpi-php:7.1 --build-arg PHP_VERSION=7.1 ./php
  
script:
  - docker images

after_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push xiaodi93/rpi-php
