version: '2.2'
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - ${HTTP_HOST}:80
      - ${HTTPS_HOST}:443
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    restart: always
  php:
    build: 
      context: ./php
      args:
        PHP_VERSION: ${PHP_VERSION}
        PHP_SWOOLE: ${PHP_SWOOLE_VERSION}
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP73_PHP_CONFIG_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP73_FPM_CONFIG_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
    cap_add:
      - SYS_PTRACE
    restart: always
    networks:
      - default
  mysql:
    image: tobi312/rpi-mysql
    volumes:
      - ./conf/my.cnf:/etc/mysql/my.cnf
      - ./data/mysql:/var/lib/mysql
    ports:
      - ${MYSQL_HOST_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
